import { Metadata } from "next";
import { SignUp } from "@/features/auth";

export const metadata: Metadata = {
  title: "Зарегистрироваться",
  description: "Generated by create next app",
};

export default async function Page() {
  return <SignUp />;
}
